### ISSUE TITLE
Use version catalog

### ISSUE THREAD

**Issue by ArnyminerZ** [ArnyminerZ/icsx5#2]

**Comment by sunkup** [comment]
Believe build time speed will only be affected if we are using "modules" in ICSx5. We are probably not going to [modularize](https://github.com/android/nowinandroid/blob/main/docs/ModularizationLearningJourney.md) ICSx5, since it is not really a big app, and I don't feel particularly overwhelmed by the codebase yet. I don't think we should create more complexity by modularizing it.

Thus the added complexity of version catalogs is not required.
